name: Deploy to Snowflake

on:
  push:
    branches:
      - sbx
  pull_request:

permissions:
      id-token: write
      contents: write
      pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: sbx
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}    

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.8.5

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan
      env:
        SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USERNAME }}
        SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        SNOWFLAKE_ORGANIZATION_NAME : ${{ secrets.SNOWFLAKE_ORGANIZATION_NAME }}
        SNOWFLAKE_ACCOUNT_NAME : ${{ secrets.SNOWFLAKE_ACCOUNT_NAME }}

    - name: Terraform Apply
      if: github.ref == 'refs/heads/sbx' && github.event_name == 'push'  
      run: terraform apply -auto-approve
      env:
        SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USERNAME }}
        SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        SNOWFLAKE_ORGANIZATION_NAME : ${{ secrets.SNOWFLAKE_ORGANIZATION_NAME }}
        SNOWFLAKE_ACCOUNT_NAME : ${{ secrets.SNOWFLAKE_ACCOUNT_NAME }}