name: Deploy to Snowflake

on:
  push:
    branches:
      - sbx
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: sbx

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.8.5

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan
      env:
        SNOWFLAKE_USER: 'github_action_user_ehsan'
        SNOWFLAKE_PASSWORD: 'DemoAzure@654321'
        SNOWFLAKE_ORGANIZATION_NAME : 'CVFSCHR'
        SNOWFLAKE_ACCOUNT_NAME : ${{ vars.SNOWFLAKE_ACCOUNT_NAME }}

    - name: Terraform Apply
      if: github.ref == 'refs/heads/sbx' && github.event_name == 'push'  
      run: terraform apply -auto-approve
      env:
        SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USERNAME }}
        SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        SNOWFLAKE_ORGANIZATION_NAME : ${{ secrets.SNOWFLAKE_ORGANIZATION_NAME }}
        SNOWFLAKE_ACCOUNT_NAME : ${{ secrets.SNOWFLAKE_ACCOUNT_NAME }}